### ISSUE TITLE
Missing Git tags

### ISSUE THREAD

**Issue by Ambrevar** [mdbergmann/cl-gserver#32]
1.7.3 and 1.7.4 are not on the public repo if I'm not mistaken.

Could you push them?  It makes it easier  for packagers to package the right version (e.g. in Nix and Guix).

**Comment by mdbergmann** [comment]
Yep, will do.
Thanks.

**Comment by mdbergmann** [comment]
Tags pushed

**Comment by Ambrevar** [comment]
Thank you!
