### ISSUE TITLE
ac:find-actors and ac:all-actors on actor

### ISSUE THREAD

**Issue by heylisp** [mdbergmann/cl-gserver#38]
Hello,
nice project!
I couldn't use (child) actors as the context to ac:find-actors and ac:all-actors. 
Is that functionality provided?
Thanks.

**Comment by mdbergmann** [comment]
`ac:find-actors` and `ac:all-actors` requires really an `actor-context` as parameter.
So this should work: `(ac:find-actors (act:context your-actor)) the-test-fun)`.

**Comment by heylisp** [comment]
Great! It worked. Thank you.
I was passing the actor itself: I understood it could be used directly in place of the actor system.
Thanks again!

**Comment by mdbergmann** [comment]
Parts of the `ac` protocol could be implemented by `actor`, like those two function which would make things a bit easier.
I'll probably do that, so reopening.

**Comment by mdbergmann** [comment]
`ac:find-actors`, `ac:find-actor-by-name` and `ac:all-actors` are now implemented by `actor`.
