### ISSUE TITLE
Hangs during build

### ISSUE THREAD

**Issue by quicklisp** [mdbergmann/cl-gserver#6]
When I try to build the latest cl-gserver, i get this during build:

``` <WARN> [10:54:29] cl-gserver gserver.lisp (handle-message fun5) - Error condition was raised on message processing: CL-GSERVER::C: #<UNDEFINED-FUNCTION NIL {100D520B13}>```

It stalls from there and does not time out or proceed.

**Comment by mdbergmann** [comment]
That's odd.
`(asdf:make :force t)` runs OK.
I've made some changes in the last couple of days. When did you pull?
The error you are getting is from running the tests.
They all run OK here using CCL.

**Comment by mdbergmann** [comment]
I found a mistake in one of the tests.
It did setup a 'nil' where a lambda was expected.
I'm greatly assuming that was the issue.
Pushed changes.

Out of curiosity, which build system do you use in Quicklisp?

**Comment by quicklisp** [comment]
This still hangs for me when using asdf:load-system to load each system in the project.

I don't understand the question about the build system, sorry.

**Comment by mdbergmann** [comment]
> I don't understand the question about the build system, sorry.

I probably meant which CL implementation.

**Comment by quicklisp** [comment]
I use SBCL 2.0.5 on 64-bit Debian Linux.

**Comment by mdbergmann** [comment]
Hmm. Weird.
Just tried on a fresh SBCL 2.0.5 upgrade on macOS.
`asdf:load-system` runs though OK.

Also tried a fresh clone, works OK as well.

I will see if I can do this on a Linux system.

**Comment by quicklisp** [comment]
It looks like it's during `Running test COUNTER-MP-BOUNDED`

**Comment by mdbergmann** [comment]
That's what the log message above suggests.
But tests should not be run until `(asdf:test-system "cl-gserver/tests")` is executed.
So I don't quite understand it.

**Comment by quicklisp** [comment]
It looks to me like `(asdf:load-system "cl-gserver/tests")` runs tests also.

**Comment by mdbergmann** [comment]
That‘s possible.
Is the test system also loaded?

**Comment by quicklisp** [comment]
I use `asdf:load-system` to load every system defined in the project.

**Comment by mdbergmann** [comment]
OK. I'll check.
While that runs tests, they should all run OK.
Or I'll see to disable running them from the individual files.

**Comment by mdbergmann** [comment]
So I tried on a Linux system. Seems the tests are disabled.
Though I need to look at this, because they actually are supposed to run.
However, for quicklisp it should be OK now.
