### ISSUE TITLE
Wrong character name: NEXT-LINE

### ISSUE THREAD

**Issue by ijitai** [mdbergmann/cl-gserver#67]
`CL-USER 11 > (ql:quickload "sento")
To load "sento":
  Load 1 ASDF system:
    sento
; Loading "sento"
[package str]

**++++ Error between functions:
  Wrong character name: NEXT-LINE.
...
; *** 1 error detected, no fasl file produced.
Error: COMPILE-FILE-ERROR while compiling #<ASDF/LISP-ACTION:CL-SOURCE-FILE "str" "str">
`

Lispworks 8.01 M1 mbp

**Comment by mdbergmann** [comment]
This looks like an issue in cl-str package on LispWorks.
Please raise issue on https://github.com/vindarel/cl-str.
This also happens when loading ‚str‘ alone.

**Comment by vindarel** [comment]
Indeed, it's a bug with LispWorks :S It's fixed, but folks using the latest Quicklisp release (Feb, 2023) will hit it. To pick the fix, you have to clone cl-str to your ~/quicklisp/local-projects, or to downgrade the QL release.

Or, go to cl-str's source and change the whitespace list to this:

```lisp
(defvar *whitespaces* (list #\Backspace #\Tab #\Linefeed #\Newline #\Vt #\Page
                            #\Return #\Space #\Rubout
                            #+sbcl #\Next-Line #-sbcl (code-char 133)  ;; <- for LW
                            #\No-break_space)
```

**Comment by mdbergmann** [comment]
Thanks for the workaround.
I'd close this ticket for the time being.
