### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by slondr** [mdbergmann/cl-gserver#83]
Hi, could installation instructions be added to the docs? 

I'm not sure how to install. I guessed that maybe I should `(ql:quickload :sento)`, but that gave me some errors:

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-C violated when interning LAMBDA-PARENT while in package
;     LOG4CL-IMPL.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 99, column: 0, position: 3779)

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD tid=8458 "main thread" RUNNING {10048481D3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">

```

**Comment by mdbergmann** [comment]
Yeah, it's just installing via quickload.

Can give some more details about your environment? Like which CL implementation and version, Linux, Mac or Windows?

**Comment by hxzrx** [comment]
You may try to use the github version of [log4cl](https://github.com/sharplispers/log4cl )

**Comment by mdbergmann** [comment]
Yeah, there is an issue in log4cl which was fixed, but quicklisp still seems to be on the 2023-10 version.
So you you can git clone log4cl to ~/quicklisp/local-projects to manually override log4cl.

**Comment by mdbergmann** [comment]
Reopen if you think it should be reopened.
