### ISSUE TITLE
Receive argument of actor-of generic-function is incorrect

### ISSUE THREAD

**Issue by svetlyak40wt** [mdbergmann/cl-gserver#85]
Docstring is [saying](https://github.com/mdbergmann/cl-gserver/blob/9d20a597395c8c183074c36b35497d9181fa7d9e/src/actor-context-api.lisp#L30-L31):

```
- `:receive` is required and must be a 3-arity lambda with arguments: 1. the actor, 2. the message, 3. the state
  Usually expressed as `(lambda (self msg state))`.
```

but actually a function of one argument is [expected](https://github.com/mdbergmann/cl-gserver/blob/9d20a597395c8c183074c36b35497d9181fa7d9e/src/actor-api.lisp#L35-L41).

**Comment by mdbergmann** [comment]
Indeed, the docstring in actor-context is wrong.
