### ISSUE TITLE
A race condition in bounded queue's pushq 

### ISSUE THREAD

**Issue by svetlyak40wt** [mdbergmann/cl-gserver#86]
Current [implementation of pushq](https://github.com/mdbergmann/cl-gserver/blob/9d20a597395c8c183074c36b35497d9181fa7d9e/src/queue/queue.lisp#L59-L60) can lead to queue overflow:

```
(defmethod pushq ((self queue-bounded) element)
  (with-slots (queue lock cvar fill-count max-items) self
    (when (>= fill-count max-items)
      (error 'queue-full-error :queue self))
    (bt2:with-lock-held (lock)
      (cl-speedy-queue:enqueue element queue)
      (incf fill-count)
      (bt2:condition-notify cvar))))
```

Between the WHEN and WITH-LOCK-HELD, some other thread might increment FILL-COUNT. WHEN form should be moved into the WITH-LOCK form.

**Comment by mdbergmann** [comment]
Yeah, you may be right. It might be safer inside the lock.

**Comment by mdbergmann** [comment]
fixed
