### ISSUE TITLE
Forced stop as a message

### ISSUE THREAD

**Issue by mdbergmann** [mdbergmann/cl-gserver#94]
Which acts similar to `act-cell:stop` method, but it more aligned with actor interface.

**Comment by adlai** [comment]
[Here's](https://github.com/adlai/scalpl/blob/master/actor.lisp#L56-L69) how I do this in my `actor.lisp`, which is probably the most notable [ab]user of ChanL.

**Comment by adlai** [comment]
Also important is [where the :halt command gets `recv`-ed](https://github.com/adlai/scalpl/blob/master/actor.lisp#L77).

To save you the trouble of distangling all that dense code, I'll paraphrase the highlighted code as follows: the chanl tasks that loop and performing each actor's work have a catch form as the topmost form in their body, and receiving the `:halt` keyword in the blessed control channel triggers the throw which immediately ends that task _without queuing its successor task_.

**Comment by mdbergmann** [comment]
Thanks. That looks straight forward. Indeed, `:halt`, or maybe I call it `:terminate` should immediately stop the message processing, but also discard any messages currently processing and any message still in the queue. Since the actor potentially doesn't operate its own thread but its mailbox is handled by one of the message-dispatcher threads it's not super trivial, but `:terminate/:halt` could just call `stop` function, which already implements what I want (or I think it does at least). Using `:terminate` should also notify watchers and distribute a `terminated` message.

**Comment by adlai** [comment]
> its mailbox is handled by one of the message-dispatcher threads it's not super trivial

this is precisely the sort of complexity that ChanL strove to avoid; one thread per task, and in my hacky actors file, one task per actor. this invariant is not perfectly maintained in the remainder of ScalpL, although I am working towards restoring it.

**Comment by mdbergmann** [comment]
Yeah, well. Actor systems still have a bit of a different use case. Actors are supposed to maintain state in a thread-safe manner. And potentially you have very many. I.e. I use Sento for Chipi (the house automation bus project) where every light, switch, window sensor and every persistence handler are represented by an actor that maintains their state. This all doesn't require more than just a very few threads.
Also Sento implements asynchronous ask pattern by spawning an anonymous actor that waits for a reply.
Other runtimes have virtual or green threads that allow this kind of things naturally, like Erlang, but in CL this sort of thing is not possible without slightly more complexity.

**Comment by adlai** [comment]
I don't think the flow I wrote works well in that case, because you couldn't predict which actors could be the ones terminating one that was given the :terminate message; similar to how you could know that if there are two light switches that toggle one bulb, then its state is effected only by one of those two switches.

**Comment by mdbergmann** [comment]
Yeah, ChanL is for running parallel tasks, not for maintaining state. But that's all fine.

**Comment by mdbergmann** [comment]
> I don't think the flow I wrote works well in that case, because you couldn't predict which actors could be the ones terminating one that was given the :terminate message; similar to how you could know that if there are two light switches that toggle one bulb, then its state is effected only by one of those two switches.
> 
> _edit, in case amateur grammar police read along: one bulb can be _**affected**_ by multiple switches, yet have its voltage _**effected**_ by touching any single switch. this is a common gimmick indispensible for corridor lighting!_

Right, but that's beyond the scope of the actor. In Chipi project this is solved by being able to setup rules.
